export const PREDEFINED_TEAMS = [
  // Premier League (39) - Custom 20 Teams requested by User
  { league_id: 39, api_team_id: 35, team_name: 'Bournemouth', team_logo: 'https://media.api-sports.io/football/teams/35.png' },
  { league_id: 39, api_team_id: 42, team_name: 'Arsenal', team_logo: 'https://media.api-sports.io/football/teams/42.png' },
  { league_id: 39, api_team_id: 66, team_name: 'Aston Villa', team_logo: 'https://media.api-sports.io/football/teams/66.png' },
  { league_id: 39, api_team_id: 55, team_name: 'Brentford', team_logo: 'https://media.api-sports.io/football/teams/55.png' },
  { league_id: 39, api_team_id: 51, team_name: 'Brighton', team_logo: 'https://media.api-sports.io/football/teams/51.png' },
  { league_id: 39, api_team_id: 49, team_name: 'Chelsea', team_logo: 'https://media.api-sports.io/football/teams/49.png' },
  { league_id: 39, api_team_id: 1346, team_name: 'Coventry', team_logo: 'https://media.api-sports.io/football/teams/1346.png' },
  { league_id: 39, api_team_id: 52, team_name: 'Crystal Palace', team_logo: 'https://media.api-sports.io/football/teams/52.png' },
  { league_id: 39, api_team_id: 45, team_name: 'Everton', team_logo: 'https://media.api-sports.io/football/teams/45.png' },
  { league_id: 39, api_team_id: 36, team_name: 'Fulham', team_logo: 'https://media.api-sports.io/football/teams/36.png' },
  { league_id: 39, api_team_id: 64, team_name: 'Hull', team_logo: 'https://media.api-sports.io/football/teams/64.png' },
  { league_id: 39, api_team_id: 57, team_name: 'Ipswich Town', team_logo: 'https://media.api-sports.io/football/teams/57.png' },
  { league_id: 39, api_team_id: 63, team_name: 'Leeds', team_logo: 'https://media.api-sports.io/football/teams/63.png' },
  { league_id: 39, api_team_id: 40, team_name: 'Liverpool', team_logo: 'https://media.api-sports.io/football/teams/40.png' },
  { league_id: 39, api_team_id: 50, team_name: 'Man City', team_logo: 'https://media.api-sports.io/football/teams/50.png' },
  { league_id: 39, api_team_id: 33, team_name: 'Man United', team_logo: 'https://media.api-sports.io/football/teams/33.png' },
  { league_id: 39, api_team_id: 34, team_name: 'Newcastle', team_logo: 'https://media.api-sports.io/football/teams/34.png' },
  { league_id: 39, api_team_id: 65, team_name: 'Nottm Forest', team_logo: 'https://media.api-sports.io/football/teams/65.png' },
  { league_id: 39, api_team_id: 746, team_name: 'Sunderland', team_logo: 'https://media.api-sports.io/football/teams/746.png' },
  { league_id: 39, api_team_id: 47, team_name: 'Spurs', team_logo: 'https://media.api-sports.io/football/teams/47.png' },

  // La Liga (140) - Sample Top Teams
  { league_id: 140, api_team_id: 541, team_name: 'Real Madrid', team_logo: 'https://media.api-sports.io/football/teams/541.png' },
  { league_id: 140, api_team_id: 529, team_name: 'Barcelona', team_logo: 'https://media.api-sports.io/football/teams/529.png' },
  { league_id: 140, api_team_id: 530, team_name: 'Atletico Madrid', team_logo: 'https://media.api-sports.io/football/teams/530.png' },
  { league_id: 140, api_team_id: 548, team_name: 'Real Sociedad', team_logo: 'https://media.api-sports.io/football/teams/548.png' },
  { league_id: 140, api_team_id: 531, team_name: 'Athletic Club', team_logo: 'https://media.api-sports.io/football/teams/531.png' },
  { league_id: 140, api_team_id: 543, team_name: 'Real Betis', team_logo: 'https://media.api-sports.io/football/teams/543.png' },
  { league_id: 140, api_team_id: 536, team_name: 'Sevilla', team_logo: 'https://media.api-sports.io/football/teams/536.png' },
  { league_id: 140, api_team_id: 532, team_name: 'Valencia', team_logo: 'https://media.api-sports.io/football/teams/532.png' },
  { league_id: 140, api_team_id: 533, team_name: 'Villarreal', team_logo: 'https://media.api-sports.io/football/teams/533.png' },
  { league_id: 140, api_team_id: 547, team_name: 'Girona', team_logo: 'https://media.api-sports.io/football/teams/547.png' },
  { league_id: 140, api_team_id: 512, team_name: 'Alaves', team_logo: 'https://media.api-sports.io/football/teams/512.png' },
  { league_id: 140, api_team_id: 538, team_name: 'Celta Vigo', team_logo: 'https://media.api-sports.io/football/teams/538.png' },
  { league_id: 140, api_team_id: 540, team_name: 'Espanyol', team_logo: 'https://media.api-sports.io/football/teams/540.png' },
  { league_id: 140, api_team_id: 546, team_name: 'Getafe', team_logo: 'https://media.api-sports.io/football/teams/546.png' },
  { league_id: 140, api_team_id: 534, team_name: 'Las Palmas', team_logo: 'https://media.api-sports.io/football/teams/534.png' },
  { league_id: 140, api_team_id: 539, team_name: 'Leganes', team_logo: 'https://media.api-sports.io/football/teams/539.png' },
  { league_id: 140, api_team_id: 798, team_name: 'Mallorca', team_logo: 'https://media.api-sports.io/football/teams/536.png' },
  { league_id: 140, api_team_id: 799, team_name: 'Osasuna', team_logo: 'https://media.api-sports.io/football/teams/529.png' },
  { league_id: 140, api_team_id: 720, team_name: 'Rayo Vallecano', team_logo: 'https://media.api-sports.io/football/teams/720.png' },
  { league_id: 140, api_team_id: 728, team_name: 'Valladolid', team_logo: 'https://media.api-sports.io/football/teams/728.png' },

  // Champions League (2) - Sample Top Teams
  { league_id: 2, api_team_id: 157, team_name: 'Bayern Munich', team_logo: 'https://media.api-sports.io/football/teams/157.png' },
  { league_id: 2, api_team_id: 85, team_name: 'PSG', team_logo: 'https://media.api-sports.io/football/teams/85.png' },
  { league_id: 2, api_team_id: 505, team_name: 'Inter Milan', team_logo: 'https://media.api-sports.io/football/teams/505.png' },
  { league_id: 2, api_team_id: 496, team_name: 'Juventus', team_logo: 'https://media.api-sports.io/football/teams/496.png' },
  { league_id: 2, api_team_id: 489, team_name: 'AC Milan', team_logo: 'https://media.api-sports.io/football/teams/489.png' },
  { league_id: 2, api_team_id: 541, team_name: 'Real Madrid (UCL)', team_logo: 'https://media.api-sports.io/football/teams/541.png' },
  { league_id: 2, api_team_id: 50, team_name: 'Man City (UCL)', team_logo: 'https://media.api-sports.io/football/teams/50.png' },
  { league_id: 2, api_team_id: 42, team_name: 'Arsenal (UCL)', team_logo: 'https://media.api-sports.io/football/teams/42.png' },
  { league_id: 2, api_team_id: 40, team_name: 'Liverpool (UCL)', team_logo: 'https://media.api-sports.io/football/teams/40.png' },
  { league_id: 2, api_team_id: 66, team_name: 'Aston Villa (UCL)', team_logo: 'https://media.api-sports.io/football/teams/66.png' },
  { league_id: 2, api_team_id: 529, team_name: 'Barcelona (UCL)', team_logo: 'https://media.api-sports.io/football/teams/529.png' },
  { league_id: 2, api_team_id: 530, team_name: 'Atletico Madrid (UCL)', team_logo: 'https://media.api-sports.io/football/teams/530.png' },
  { league_id: 2, api_team_id: 110, team_name: 'Bayer Leverkusen', team_logo: 'https://media.api-sports.io/football/teams/110.png' },
  { league_id: 2, api_team_id: 173, team_name: 'RB Leipzig', team_logo: 'https://media.api-sports.io/football/teams/173.png' },
  { league_id: 2, api_team_id: 168, team_name: 'B. Dortmund', team_logo: 'https://media.api-sports.io/football/teams/168.png' },
  { league_id: 2, api_team_id: 492, team_name: 'Napoli', team_logo: 'https://media.api-sports.io/football/teams/492.png' },
  { league_id: 2, api_team_id: 497, team_name: 'AS Roma', team_logo: 'https://media.api-sports.io/football/teams/497.png' },
  { league_id: 2, api_team_id: 228, team_name: 'Porto', team_logo: 'https://media.api-sports.io/football/teams/228.png' },
  { league_id: 2, api_team_id: 211, team_name: 'Benfica', team_logo: 'https://media.api-sports.io/football/teams/211.png' },
  { league_id: 2, api_team_id: 229, team_name: 'Sporting CP', team_logo: 'https://media.api-sports.io/football/teams/228.png' },
  { league_id: 2, api_team_id: 197, team_name: 'PSV', team_logo: 'https://media.api-sports.io/football/teams/197.png' },
  { league_id: 2, api_team_id: 209, team_name: 'Feyenoord', team_logo: 'https://media.api-sports.io/football/teams/209.png' },
  { league_id: 2, api_team_id: 194, team_name: 'Ajax', team_logo: 'https://media.api-sports.io/football/teams/194.png' },
  { league_id: 2, api_team_id: 569, team_name: 'Club Brugge', team_logo: 'https://media.api-sports.io/football/teams/569.png' },
  { league_id: 2, api_team_id: 61, team_name: 'Celtic', team_logo: 'https://media.api-sports.io/football/teams/61.png' },
  { league_id: 2, api_team_id: 62, team_name: 'Rangers', team_logo: 'https://media.api-sports.io/football/teams/62.png' },
  { league_id: 2, api_team_id: 645, team_name: 'Galatasaray', team_logo: 'https://media.api-sports.io/football/teams/645.png' },
  { league_id: 2, api_team_id: 643, team_name: 'Fenerbahce', team_logo: 'https://media.api-sports.io/football/teams/643.png' },
  { league_id: 2, api_team_id: 550, team_name: 'Shakhtar', team_logo: 'https://media.api-sports.io/football/teams/550.png' },
  { league_id: 2, api_team_id: 571, team_name: 'RB Salzburg', team_logo: 'https://media.api-sports.io/football/teams/571.png' },
  { league_id: 2, api_team_id: 91, team_name: 'Monaco', team_logo: 'https://media.api-sports.io/football/teams/91.png' },
  { league_id: 2, api_team_id: 79, team_name: 'Lille', team_logo: 'https://media.api-sports.io/football/teams/79.png' }
];
