export const PREDEFINED_TEAMS = [
  // Premier League (39) - Custom 20 Teams requested by User
  { league_id: 39, api_team_id: 35, team_name: 'Bournemouth', team_logo: 'https://media.api-sports.io/football/teams/35.png' },
  { league_id: 39, api_team_id: 42, team_name: 'Arsenal', team_logo: 'https://media.api-sports.io/football/teams/42.png' },
  { league_id: 39, api_team_id: 66, team_name: 'Aston Villa', team_logo: 'https://media.api-sports.io/football/teams/66.png' },
  { league_id: 39, api_team_id: 55, team_name: 'Brentford', team_logo: 'https://media.api-sports.io/football/teams/55.png' },
  { league_id: 39, api_team_id: 51, team_name: 'Brighton', team_logo: 'https://media.api-sports.io/football/teams/51.png' },
  { league_id: 39, api_team_id: 49, team_name: 'Chelsea', team_logo: 'https://media.api-sports.io/football/teams/49.png' },
  { league_id: 39, api_team_id: 1346, team_name: 'Coventry', team_logo: 'https://media.api-sports.io/football/teams/1346.png' },
  { league_id: 39, api_team_id: 52, team_name: 'Crystal Palace', team_logo: 'https://media.api-sports.io/football/teams/52.png' },
  { league_id: 39, api_team_id: 45, team_name: 'Everton', team_logo: 'https://media.api-sports.io/football/teams/45.png' },
  { league_id: 39, api_team_id: 36, team_name: 'Fulham', team_logo: 'https://media.api-sports.io/football/teams/36.png' },
  { league_id: 39, api_team_id: 64, team_name: 'Hull', team_logo: 'https://media.api-sports.io/football/teams/64.png' },
  { league_id: 39, api_team_id: 57, team_name: 'Ipswich Town', team_logo: 'https://media.api-sports.io/football/teams/57.png' },
  { league_id: 39, api_team_id: 63, team_name: 'Leeds', team_logo: 'https://media.api-sports.io/football/teams/63.png' },
  { league_id: 39, api_team_id: 40, team_name: 'Liverpool', team_logo: 'https://media.api-sports.io/football/teams/40.png' },
  { league_id: 39, api_team_id: 50, team_name: 'Man City', team_logo: 'https://media.api-sports.io/football/teams/50.png' },
  { league_id: 39, api_team_id: 33, team_name: 'Man United', team_logo: 'https://media.api-sports.io/football/teams/33.png' },
  { league_id: 39, api_team_id: 34, team_name: 'Newcastle', team_logo: 'https://media.api-sports.io/football/teams/34.png' },
  { league_id: 39, api_team_id: 65, team_name: 'Nottm Forest', team_logo: 'https://media.api-sports.io/football/teams/65.png' },
  { league_id: 39, api_team_id: 746, team_name: 'Sunderland', team_logo: 'https://media.api-sports.io/football/teams/746.png' },
  { league_id: 39, api_team_id: 47, team_name: 'Spurs', team_logo: 'https://media.api-sports.io/football/teams/47.png' },

  // La Liga (140) - Sample Top Teams
  { league_id: 140, api_team_id: 541, team_name: 'Real Madrid', team_logo: 'https://media.api-sports.io/football/teams/541.png' },
  { league_id: 140, api_team_id: 529, team_name: 'Barcelona', team_logo: 'https://media.api-sports.io/football/teams/529.png' },
  { league_id: 140, api_team_id: 530, team_name: 'Atletico Madrid', team_logo: 'https://media.api-sports.io/football/teams/530.png' },
  { league_id: 140, api_team_id: 548, team_name: 'Real Sociedad', team_logo: 'https://media.api-sports.io/football/teams/548.png' },
  { league_id: 140, api_team_id: 531, team_name: 'Athletic Club', team_logo: 'https://media.api-sports.io/football/teams/531.png' },
  { league_id: 140, api_team_id: 543, team_name: 'Real Betis', team_logo: 'https://media.api-sports.io/football/teams/543.png' },
  { league_id: 140, api_team_id: 536, team_name: 'Sevilla', team_logo: 'https://media.api-sports.io/football/teams/536.png' },
  { league_id: 140, api_team_id: 532, team_name: 'Valencia', team_logo: 'https://media.api-sports.io/football/teams/532.png' },
  { league_id: 140, api_team_id: 533, team_name: 'Villarreal', team_logo: 'https://media.api-sports.io/football/teams/533.png' },
  { league_id: 140, api_team_id: 512, team_name: 'Alaves', team_logo: 'https://media.api-sports.io/football/teams/512.png' },
  { league_id: 140, api_team_id: 538, team_name: 'Celta Vigo', team_logo: 'https://media.api-sports.io/football/teams/538.png' },
  { league_id: 140, api_team_id: 540, team_name: 'Espanyol', team_logo: 'https://media.api-sports.io/football/teams/540.png' },
  { league_id: 140, api_team_id: 546, team_name: 'Getafe', team_logo: 'https://media.api-sports.io/football/teams/546.png' },
  { league_id: 140, api_team_id: 799, team_name: 'Osasuna', team_logo: 'https://media.api-sports.io/football/teams/529.png' },
  { league_id: 140, api_team_id: 720, team_name: 'Rayo Vallecano', team_logo: 'https://media.api-sports.io/football/teams/720.png' },

  // Champions League (2) - Sample Top Teams
  { league_id: 2, api_team_id: 157, team_name: 'Bayern Munich', team_logo: 'https://media.api-sports.io/football/teams/157.png' },
  { league_id: 2, api_team_id: 85, team_name: 'PSG', team_logo: 'https://media.api-sports.io/football/teams/85.png' },
  { league_id: 2, api_team_id: 505, team_name: 'Inter Milan', team_logo: 'https://media.api-sports.io/football/teams/505.png' },
  { league_id: 2, api_team_id: 496, team_name: 'Juventus', team_logo: 'https://media.api-sports.io/football/teams/496.png' },
  { league_id: 2, api_team_id: 489, team_name: 'AC Milan', team_logo: 'https://media.api-sports.io/football/teams/489.png' },
  { league_id: 2, api_team_id: 541, team_name: 'Real Madrid (UCL)', team_logo: 'https://media.api-sports.io/football/teams/541.png' },
  { league_id: 2, api_team_id: 50, team_name: 'Man City (UCL)', team_logo: 'https://media.api-sports.io/football/teams/50.png' },
  { league_id: 2, api_team_id: 42, team_name: 'Arsenal (UCL)', team_logo: 'https://media.api-sports.io/football/teams/42.png' },
  { league_id: 2, api_team_id: 40, team_name: 'Liverpool (UCL)', team_logo: 'https://media.api-sports.io/football/teams/40.png' },
  { league_id: 2, api_team_id: 66, team_name: 'Aston Villa (UCL)', team_logo: 'https://media.api-sports.io/football/teams/66.png' },
  { league_id: 2, api_team_id: 529, team_name: 'Barcelona (UCL)', team_logo: 'https://media.api-sports.io/football/teams/529.png' },
  { league_id: 2, api_team_id: 530, team_name: 'Atletico Madrid (UCL)', team_logo: 'https://media.api-sports.io/football/teams/530.png' },
  { league_id: 2, api_team_id: 168, team_name: 'Bayer Leverkusen', team_logo: 'https://media.api-sports.io/football/teams/168.png' },
  { league_id: 2, api_team_id: 173, team_name: 'RB Leipzig', team_logo: 'https://media.api-sports.io/football/teams/173.png' },
  { league_id: 2, api_team_id: 165, team_name: 'B. Dortmund', team_logo: 'https://media.api-sports.io/football/teams/165.png' },
  { league_id: 2, api_team_id: 492, team_name: 'Napoli', team_logo: 'https://media.api-sports.io/football/teams/492.png' },
  { league_id: 2, api_team_id: 497, team_name: 'AS Roma', team_logo: 'https://media.api-sports.io/football/teams/497.png' },
  { league_id: 2, api_team_id: 228, team_name: 'Porto', team_logo: 'https://media.api-sports.io/football/teams/228.png' },
  { league_id: 2, api_team_id: 211, team_name: 'Benfica', team_logo: 'https://media.api-sports.io/football/teams/211.png' },
  { league_id: 2, api_team_id: 229, team_name: 'Sporting CP', team_logo: 'https://media.api-sports.io/football/teams/228.png' },
  { league_id: 2, api_team_id: 197, team_name: 'PSV', team_logo: 'https://media.api-sports.io/football/teams/197.png' },
  { league_id: 2, api_team_id: 209, team_name: 'Feyenoord', team_logo: 'https://media.api-sports.io/football/teams/209.png' },
  { league_id: 2, api_team_id: 194, team_name: 'Ajax', team_logo: 'https://media.api-sports.io/football/teams/194.png' },
  { league_id: 2, api_team_id: 569, team_name: 'Club Brugge', team_logo: 'https://media.api-sports.io/football/teams/569.png' },
  { league_id: 2, api_team_id: 61, team_name: 'Celtic', team_logo: 'https://media.api-sports.io/football/teams/61.png' },
  { league_id: 2, api_team_id: 62, team_name: 'Rangers', team_logo: 'https://media.api-sports.io/football/teams/62.png' },
  { league_id: 2, api_team_id: 645, team_name: 'Galatasaray', team_logo: 'https://media.api-sports.io/football/teams/645.png' },
  { league_id: 2, api_team_id: 643, team_name: 'Fenerbahce', team_logo: 'https://media.api-sports.io/football/teams/643.png' },
  { league_id: 2, api_team_id: 550, team_name: 'Shakhtar', team_logo: 'https://media.api-sports.io/football/teams/550.png' },
  { league_id: 2, api_team_id: 571, team_name: 'RB Salzburg', team_logo: 'https://media.api-sports.io/football/teams/571.png' },
  { league_id: 2, api_team_id: 91, team_name: 'Monaco', team_logo: 'https://media.api-sports.io/football/teams/91.png' },
  { league_id: 2, api_team_id: 79, team_name: 'Lille', team_logo: 'https://media.api-sports.io/football/teams/79.png' },

  
  // --- NEW TEAMS 2026 ---
  { league_id: 140, api_team_id: 84, team_name: 'Malaga', team_logo: 'https://crests.football-data.org/84.png' },
  { league_id: 140, api_team_id: 88, team_name: 'Levante', team_logo: 'https://crests.football-data.org/88.png' },
  { league_id: 140, api_team_id: 285, team_name: 'Elche', team_logo: 'https://crests.football-data.org/285.png' },
  { league_id: 140, api_team_id: 560, team_name: 'Deportivo La Coruna', team_logo: 'https://crests.football-data.org/560.png' },
  { league_id: 140, api_team_id: 5335, team_name: 'Racing Santander', team_logo: 'https://crests.football-data.org/5335.png' },
  // --- NEW LEAGUES EXTENSION ---
  // Bundesliga
  { league_id: 78, api_team_id: 1, team_name: '1. FC Köln', team_logo: 'https://crests.football-data.org/1.png' },
  { league_id: 78, api_team_id: 167, team_name: 'TSG 1899 Hoffenheim', team_logo: 'https://crests.football-data.org/2.png' },
  { league_id: 78, api_team_id: 168, team_name: 'Bayer 04 Leverkusen', team_logo: 'https://media.api-sports.io/football/teams/168.png' },
  { league_id: 78, api_team_id: 165, team_name: 'Borussia Dortmund', team_logo: 'https://crests.football-data.org/4.png' },
  { league_id: 78, api_team_id: 157, team_name: 'FC Bayern München', team_logo: 'https://crests.football-data.org/5.png' },
  { league_id: 78, api_team_id: 6, team_name: 'FC Schalke 04', team_logo: 'https://crests.football-data.org/6.png' },
  { league_id: 78, api_team_id: 7, team_name: 'Hamburger SV', team_logo: 'https://crests.football-data.org/7.png' },
  { league_id: 78, api_team_id: 172, team_name: 'VfB Stuttgart', team_logo: 'https://crests.football-data.org/10.png' },
  { league_id: 78, api_team_id: 162, team_name: 'SV Werder Bremen', team_logo: 'https://crests.football-data.org/12.png' },
  { league_id: 78, api_team_id: 164, team_name: '1. FSV Mainz 05', team_logo: 'https://crests.football-data.org/15.png' },
  { league_id: 78, api_team_id: 170, team_name: 'FC Augsburg', team_logo: 'https://crests.football-data.org/16.png' },
  { league_id: 78, api_team_id: 160, team_name: 'SC Freiburg', team_logo: 'https://crests.football-data.org/17.png' },
  { league_id: 78, api_team_id: 163, team_name: 'Borussia Mönchengladbach', team_logo: 'https://crests.football-data.org/18.png' },
  { league_id: 78, api_team_id: 169, team_name: 'Eintracht Frankfurt', team_logo: 'https://crests.football-data.org/19.png' },
  { league_id: 78, api_team_id: 182, team_name: '1. FC Union Berlin', team_logo: 'https://crests.football-data.org/28.png' },
  { league_id: 78, api_team_id: 29, team_name: 'SC Paderborn 07', team_logo: 'https://crests.football-data.org/29.png' },
  { league_id: 78, api_team_id: 719, team_name: 'SV 07 Elversberg', team_logo: 'https://crests.football-data.org/719.png' },
  // Serie A
  { league_id: 135, api_team_id: 502, team_name: 'ACF Fiorentina', team_logo: 'https://crests.football-data.org/99.png' },
  { league_id: 135, api_team_id: 499, team_name: 'Atalanta BC', team_logo: 'https://crests.football-data.org/102.png' },
  { league_id: 135, api_team_id: 500, team_name: 'Bologna FC 1909', team_logo: 'https://crests.football-data.org/103.png' },
  { league_id: 135, api_team_id: 490, team_name: 'Cagliari Calcio', team_logo: 'https://crests.football-data.org/104.png' },
  { league_id: 135, api_team_id: 495, team_name: 'Genoa CFC', team_logo: 'https://crests.football-data.org/107.png' },
  { league_id: 135, api_team_id: 505, team_name: 'FC Internazionale Milano', team_logo: 'https://crests.football-data.org/108.png' },
  { league_id: 135, api_team_id: 496, team_name: 'Juventus FC', team_logo: 'https://crests.football-data.org/109.png' },
  { league_id: 135, api_team_id: 487, team_name: 'SS Lazio', team_logo: 'https://crests.football-data.org/110.png' },
  { league_id: 135, api_team_id: 523, team_name: 'Parma Calcio 1913', team_logo: 'https://crests.football-data.org/112.png' },
  { league_id: 135, api_team_id: 492, team_name: 'SSC Napoli', team_logo: 'https://crests.football-data.org/113.png' },
  { league_id: 135, api_team_id: 494, team_name: 'Udinese Calcio', team_logo: 'https://crests.football-data.org/115.png' },
  { league_id: 135, api_team_id: 517, team_name: 'Venezia FC', team_logo: 'https://crests.football-data.org/454.png' },
  { league_id: 135, api_team_id: 470, team_name: 'Frosinone Calcio', team_logo: 'https://crests.football-data.org/470.png' },
  { league_id: 135, api_team_id: 471, team_name: 'US Sassuolo Calcio', team_logo: 'https://crests.football-data.org/471.png' },
  { league_id: 135, api_team_id: 503, team_name: 'Torino FC', team_logo: 'https://crests.football-data.org/586.png' },
  { league_id: 135, api_team_id: 867, team_name: 'US Lecce', team_logo: 'https://crests.football-data.org/5890.png' },
  { league_id: 135, api_team_id: 1579, team_name: 'AC Monza', team_logo: 'https://crests.football-data.org/5911.png' },
  { league_id: 135, api_team_id: 895, team_name: 'Como 1907', team_logo: 'https://crests.football-data.org/7397.png' },
  // Ligue 1
  { league_id: 61, api_team_id: 96, team_name: 'Toulouse FC', team_logo: 'https://crests.football-data.org/511.png' },
  { league_id: 61, api_team_id: 106, team_name: 'Stade Brestois 29', team_logo: 'https://crests.football-data.org/512.png' },
  { league_id: 61, api_team_id: 81, team_name: 'Olympique de Marseille', team_logo: 'https://crests.football-data.org/516.png' },
  { league_id: 61, api_team_id: 108, team_name: 'AJ Auxerre', team_logo: 'https://crests.football-data.org/519.png' },
  { league_id: 61, api_team_id: 79, team_name: 'Lille OSC', team_logo: 'https://crests.football-data.org/521.png' },
  { league_id: 61, api_team_id: 84, team_name: 'OGC Nice', team_logo: 'https://crests.football-data.org/522.png' },
  { league_id: 61, api_team_id: 80, team_name: 'Olympique Lyonnais', team_logo: 'https://crests.football-data.org/523.png' },
  { league_id: 61, api_team_id: 85, team_name: 'Paris Saint-Germain FC', team_logo: 'https://crests.football-data.org/524.png' },
  { league_id: 61, api_team_id: 525, team_name: 'FC Lorient', team_logo: 'https://crests.football-data.org/525.png' },
  { league_id: 61, api_team_id: 94, team_name: 'Stade Rennais FC 1901', team_logo: 'https://crests.football-data.org/529.png' },
  { league_id: 61, api_team_id: 531, team_name: 'ES Troyes AC', team_logo: 'https://crests.football-data.org/531.png' },
  { league_id: 61, api_team_id: 77, team_name: 'Angers SCO', team_logo: 'https://crests.football-data.org/532.png' },
  { league_id: 61, api_team_id: 111, team_name: 'Le Havre AC', team_logo: 'https://crests.football-data.org/533.png' },
  { league_id: 61, api_team_id: 535, team_name: 'Le Mans FC', team_logo: 'https://upload.wikimedia.org/wikipedia/en/5/57/Le_Mans_FC_logo.svg' },
  { league_id: 61, api_team_id: 116, team_name: 'Racing Club de Lens', team_logo: 'https://crests.football-data.org/546.png' },
  { league_id: 61, api_team_id: 91, team_name: 'AS Monaco FC', team_logo: 'https://crests.football-data.org/548.png' },
  { league_id: 61, api_team_id: 95, team_name: 'RC Strasbourg Alsace', team_logo: 'https://crests.football-data.org/576.png' },
  { league_id: 61, api_team_id: 85, team_name: 'Paris FC', team_logo: 'https://crests.football-data.org/1045.png' },
  ];

